name: todo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  dio: ^4.0.6
  get: ^4.6.6
  floor: ^1.1.0
  intl: ^0.18.0
  dartz: ^0.10.1
  get_it: ^7.2.0
  lottie: ^2.3.2
  timeago: ^3.2.2
  provider: ^6.0.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  infinite_scroll_pagination: ^4.0.0
  shared_preferences: ^2.0.15
  percent_indicator: ^4.2.3
  flutter_tts: ^3.6.3
  fluttertoast: ^8.1.1
  animations: any
  pretty_dio_logger: ^1.1.1
  flutter_cache_manager: ^3.3.0
  flutter_locales:
  font_awesome_flutter: 10.1.0
  permission_handler: ^9.2.0
  flutter_svg: any
  jwt_decoder: ^2.0.1
  flutter_progress_hud: ^2.0.2
  scrollable_positioned_list: ^0.3.5
  dropdown_button2: ^1.9.0
  flutter_secure_storage: ^8.0.0
  introduction_screen: ^3.1.4
  google_fonts: ^4.0.4
  youtube_player_flutter: ^8.1.0
  badges: ^2.0.1
  google_place: ^0.4.7
  google_places_flutter: ^2.0.6
  url_launcher: ^6.0.12
  flutter_boxicons: ^3.0.0
  image_picker: ^0.8.1+1
  flutter_calendar_carousel: ^2.0.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.3
  firebase_core_platform_interface: ^5.0.0
  another_flushbar: ^1.12.29
  syncfusion_flutter_charts: ^21.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  ios: true
  android: "launcher_icon"
  remove_alpha_ios: true
  image_path: "assets/Launcher_Icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/notifications.json


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-VariableFont_wght.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
