// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybiK0fDl3aMcs1Xa4AeZWrutxraZAmGM',
    appId: '1:143381014139:android:dbc7bf5b6c3e58222724de',
    messagingSenderId: '143381014139',
    projectId: 'todo-app',
    // authDomain: 'vinciioflutter.firebaseapp.com',
    // storageBucket: 'vinciioflutter.appspot.com',
    // measurementId: 'G-Z8ZZT0G611',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyAybiK0fDl3aMcs1Xa4AeZWrutxraZAmGM',
      appId: '1:143381014139:android:dbc7bf5b6c3e58222724de',
      messagingSenderId: '143381014139',
      projectId: 'todo-app');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybiK0fDl3aMcs1Xa4AeZWrutxraZAmGM',
    appId: '1:143381014139:android:dbc7bf5b6c3e58222724de',
    messagingSenderId: '143381014139',
    projectId: 'todo-app',
    iosClientId: '143381014139-dtbdfnobfnsfis7advljrbq4h5pr11ti.apps.googleusercontent.com',
    iosBundleId: 'com.app.todoSchools',
  );
}
